feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggingLevel: basic
      currencyClient:
        defaultRequestHeaders:
          Authorization: Token ${api.currency.appId}
      giphyApiClient:
        defaultQueryParameters:
          api_key: ${api.giphy-api.appId}

api:
  currency:
    url: https://openexchangerates.org
  giphy-api:
    url: https://api.giphy.com
  giphy-media:
    url: https://media2.giphy.com
server:
  port: 8081
  error:
    include-message: always

baseCurrency: RUB